config/routes.rb
Rails.application.routes.draw do
  resources :slides

end

app/models/slide.rb
class Slide < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sliders</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc %></td>
        <td><%= slide.author %></td>
        <td><%= link_to 'Show', slide %></td>
        <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @slide.desc %>
</p>

<p>
  <strong>Author:</strong>
  <%= @slide.author %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>